# Generated by Django 3.2.2 on 2010-01-06 18:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=3000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('category_name', models.CharField(choices=[('business', 'Business'), ('technology', 'Technology'), ('internet', 'Internet'), ('tutorials', 'Tutorials'), ('finance', 'Finance'), ('monetary', 'Monetary'), ('online-business', 'Online Business'), ('lifestyle', 'Lifestyle'), ('sports', 'Sports'), ('politics', 'Politics'), ('health', 'Health'), ('science', 'Science'), ('entertainment', 'Entertainment'), ('programming', 'Programming'), ('how-to', 'How-to'), ('educational', 'Educational')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date_subscibed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='xtrablog/images/mails')),
                ('message', models.TextField(blank=True, max_length=3000, null=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XtraBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=50)),
                ('email2', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=200)),
                ('facebook_link', models.CharField(blank=True, max_length=200)),
                ('instagram_link', models.CharField(blank=True, max_length=200)),
                ('twitter_link', models.CharField(blank=True, max_length=200)),
                ('linked_in', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('newsletter_password', models.CharField(blank=True, max_length=200, null=True)),
                ('google_analytics', models.TextField(blank=True, max_length=2000, null=True)),
                ('retangular_ad', models.TextField(blank=True, max_length=2000, null=True)),
                ('square_ad', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('reply', models.TextField(max_length=3000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='xtrablog/images/users/default.jpg', upload_to='xtrablog/images/users')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, max_length=750, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='xtrablog/images/blog')),
                ('image1_url', models.URLField(blank=True, max_length=3000, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='xtrablog/images/blog')),
                ('image2_url', models.URLField(blank=True, max_length=3000, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='xtrablog/images/blog')),
                ('image3_url', models.URLField(blank=True, max_length=3000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='xtrablog/videos')),
                ('video_url', models.URLField(blank=True, max_length=3000, null=True)),
                ('youtube', models.URLField(blank=True, max_length=3000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='xtrablog/documents')),
                ('content', ckeditor.fields.RichTextField(max_length=25000)),
                ('link', models.CharField(blank=True, max_length=3000, null=True)),
                ('link_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(max_length=150, null=True)),
                ('meta_description', models.CharField(max_length=160, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.postcategory')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
