# Generated by Django 3.2.2 on 2022-01-18 02:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('category_name', models.CharField(choices=[('business', 'Business'), ('web', 'Web Development'), ('graphics', 'Graphic design'), ('technology', 'Technology'), ('internet', 'Internet'), ('tutorials', 'Tutorials'), ('finance', 'Finance'), ('monetary', 'Monetary'), ('online-business', 'Online Business'), ('lifestyle', 'Lifestyle'), ('python', 'Python'), ('javascript', 'Javascript')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Images/blog')),
                ('image1_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Images/blog')),
                ('image2_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Images/blog')),
                ('image3_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='Videos')),
                ('video_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('youtube', models.CharField(blank=True, max_length=3000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='Documents')),
                ('paragraph1', models.TextField(max_length=10000)),
                ('paragraph2', models.TextField(blank=True, max_length=10000, null=True)),
                ('paragraph3', models.TextField(blank=True, max_length=10000, null=True)),
                ('paragraph4', models.TextField(blank=True, max_length=10000, null=True)),
                ('paragraph5', models.TextField(blank=True, max_length=10000, null=True)),
                ('link', models.CharField(blank=True, max_length=3000, null=True)),
                ('link_description', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.postcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, max_length=3000, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
