# Generated by Django 3.2.2 on 2022-10-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribersMail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube',
            field=models.TextField(blank=True, help_text='Youtube video embedded code', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_name',
            field=models.CharField(choices=[('business', 'Business'), ('technology', 'Technology'), ('internet', 'Internet'), ('tutorials', 'Tutorials'), ('finance', 'Finance'), ('monetary', 'Monetary'), ('online business', 'Online Business'), ('lifestyle', 'Lifestyle'), ('sports', 'Sports'), ('politics', 'Politics'), ('health', 'Health'), ('science', 'Science'), ('art', 'Art'), ('news', 'News'), ('commercial', 'Commercial'), ('entertainment', 'Entertainment'), ('programming', 'Programming'), ('how tos', 'How tos'), ('educational', 'Educational'), ('others', 'Others')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='linked_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='whatsapp number', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='xtrablog',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
