# Generated by Django 3.2.2 on 2022-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20221024_0449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XtraBlog',
        ),
    ]
