# Generated by Django 3.2.2 on 2022-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_name',
            field=models.CharField(choices=[('business', 'Business'), ('web', 'Web Development'), ('graphics', 'Graphic design'), ('technology', 'Technology'), ('internet', 'Internet'), ('tutorials', 'Tutorials'), ('finance', 'Finance'), ('monetary', 'Monetary'), ('online-business', 'Online Business'), ('lifestyle', 'Lifestyle'), ('python', 'Python'), ('javascript', 'Javascript'), ('sports', 'Sports'), ('politics', 'Politics'), ('health', 'Health'), ('science', 'Science'), ('entertainment', 'Entertainment'), ('life-hacks', 'Life hacks')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
