# Generated by Django 3.2.2 on 2022-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_delete_xtrablog'),
    ]

    operations = [
        migrations.CreateModel(
            name='XtraBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=50)),
                ('email2', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='whatsapp number', max_length=25, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('newsletter_password', models.CharField(blank=True, max_length=200, null=True)),
                ('google_analytics', models.TextField(blank=True, max_length=2000, null=True)),
                ('retangular_ad', models.TextField(blank=True, max_length=2000, null=True)),
                ('square_ad', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
