# Generated by Django 3.2.2 on 2022-03-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0007_auto_20220303_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date_subscibed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='Images/subscribers')),
                ('message', models.TextField(blank=True, max_length=3000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XtraBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=50)),
                ('email2', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=200)),
                ('facebook_link', models.CharField(blank=True, max_length=200)),
                ('instagram_link', models.CharField(blank=True, max_length=200)),
                ('twitter_link', models.CharField(blank=True, max_length=200)),
                ('linked_in', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_name',
            field=models.CharField(choices=[('business', 'Business'), ('technology', 'Technology'), ('internet', 'Internet'), ('tutorials', 'Tutorials'), ('finance', 'Finance'), ('monetary', 'Monetary'), ('online-business', 'Online Business'), ('lifestyle', 'Lifestyle'), ('sports', 'Sports'), ('politics', 'Politics'), ('health', 'Health'), ('science', 'Science'), ('entertainment', 'Entertainment'), ('programming', 'Programming'), ('how-to', 'How-to'), ('educational', 'Educational')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='Images/users/default.jpg', upload_to='Images/users')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('rectangular_ad1', models.TextField(blank=True, max_length=2000, null=True)),
                ('rectangular_ad2', models.TextField(blank=True, max_length=2000, null=True)),
                ('square_ad', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
